DROP TABLE [3FG].CANCELACIONES;
GO
DROP TABLE [3FG].ATENCIONES_MEDICAS;
GO
DROP TABLE [3FG].RECEPCIONES;
GO
DROP TABLE [3FG].AGENDA;
GO
DROP TABLE [3FG].TURNOS;
GO
DROP TABLE [3FG].ESPECIALIDAD_PROFESIONAL;
GO
DROP TABLE [3FG].ESPECIALIDADES;
GO
DROP TABLE [3FG].TIPO_ESPECIALIDAD;
GO
DROP TABLE [3FG].PROFESIONALES;
GO
DROP TABLE [3FG].HISTORIAL_CAMBIOS_PLAN;
GO
DROP TABLE [3FG].BONOS;
GO
DROP TABLE [3FG].AFILIADOS;
GO
DROP TABLE [3FG].PLANES;
GO
DROP TABLE [3FG].COMPRAS;
GO
DROP TABLE [3FG].ROLES_USUARIO;
GO
DROP TABLE [3FG].FUNCIONALIDADES_ROL;
GO
DROP TABLE [3FG].ROLES;
GO
DROP TABLE [3FG].FUNCIONALIDADES;
GO
DROP TABLE [3FG].USUARIOS;
GO
